### ISSUE TITLE
[epic] expedited this week

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#290]
- [X] move this week space to dock under today
- [X] change backend accordingly, auto create 3 spaces instead of 4 @sajdakabir

move items with status ' todo, 'in progress' to 'next week' when a week ends —
[SAT-251](https://linear.app/marchhq/issue/SAT-251/move-cycledate-over-due-items-to-next-cycle)

UI

- [X] expanded view opens like a sheet overlapping done section in order to make the ui stable.
- [X] fix alignment of input title.
- [X] fix pointer issue when clicked on 'add an item' ( now the pointer needs to be there manually to type)
- [X] show " + add an item" on hover

[SAT-238](https://linear.app/marchhq/issue/SAT-238/show-add-an-item-in-todo-section-in-empty-week) ( when items presents, it shows on hover)

- [X] add reschedule, delete as props in expanded view.
- [X] add scroll on sections

[SAT-239](https://linear.app/marchhq/issue/SAT-239/make-scroll-invisible-in-weeks-status-sections)

- [X] add hover of the item when expanded view in use

[SAT-248](https://linear.app/marchhq/issue/SAT-248/week-backward-forward-functionality)

New items added being shown on top in case of multiple items in that section, instead show that just above the input bar. ( in inbox we are following write and shows down, here we do the opposite)

[SAT-255](https://linear.app/marchhq/issue/SAT-255/show-new-items-added-on-top-of-editor-instead-of-top-of-the-section)

Note: items in notes, reading list and other spaces, shows in this week when there is a due date prop but that does not change their source ( existing space) to this week. only prop changes reflects to their source in expanded view.
