### ISSUE TITLE
websocket maximise on fe [epic]

### ISSUE THREAD

**Issue by immadsahin** [emptyarrayhq/emptyarray#678]
- [X] in the deployed version web socket is working
- [X] Establish a WebSocket connection that is specific to the user./or add encryption
- [X] sending binary data
- [X] like inbox needs to update state in today, this week @dazai
- [X] in inbox– deleted a item is not handled @dazai
- [X] added auto the the socket
- [ ]
